version: '2'

services:
  dummy-webhook:
    build:
      context: ./web/
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/certificates:/etc/dummy/certificates

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "5000:80"
    links:
      - dummy-webhook
    volumes:
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled
      - ./nginx/certificates:/etc/nginx/certificates
      - /etc/ssl/certs:/etc/ssl/certs
